Add files via upload
changed low_memory to True due to error

Traceback (most recent call last):
  File "/home/pi/Documents/vaers.py", line 56, in <module>
    df1 = pd.read_csv(dbfile, encoding='latin1',thousands=',', low_memory=False, usecols = ['VAERS_ID','RECVDATE','SYMPTOM_TEXT','STATE','AGE_YRS','DIED'])
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 228, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 783, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 872, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: out of memory